services:

  database:
    image: docker.io/postgres:17-alpine
    environment:
      POSTGRES_USER: stustapay
      POSTGRES_DB: stustapay
      POSTGRES_PASSWORD: stustapay
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: on-failure
    healthcheck:
      test: ["CMD", "/usr/local/bin/pg_isready -u stustapay"]
      start_period: 10s

  help:
    build:
      context: ..
      dockerfile: compose/Dockerfile.be
      args:
        - DOMAIN_NAME=$DOMAIN_NAME
        - APP_SECRET_TOKEN=$APP_SECRET_TOKEN
    command: /usr/local/bin/stustapay --help
    restart: on-failure

  dbupdate:
    build:
      context: ..
      dockerfile: compose/Dockerfile.be
      args:
        - DOMAIN_NAME=$DOMAIN_NAME
        - APP_SECRET_TOKEN=$APP_SECRET_TOKEN
    command: /usr/local/bin/stustapay db migrate
    restart: on-failure
    depends_on:
      - database

  administration-api:
    build:
      context: ..
      dockerfile: compose/Dockerfile.be
      args:
        - DOMAIN_NAME=$DOMAIN_NAME
        - APP_SECRET_TOKEN=$APP_SECRET_TOKEN
    command: /usr/local/bin/stustapay administration-api
    restart: on-failure
    depends_on:
      dbupdate:
        condition: service_completed_successfully

  customerportal-api:
    build:
      context: ..
      dockerfile: compose/Dockerfile.be
      args:
        - DOMAIN_NAME=$DOMAIN_NAME
        - APP_SECRET_TOKEN=$APP_SECRET_TOKEN
    command: /usr/local/bin/stustapay customerportal-api
    restart: on-failure
    depends_on:
      dbupdate:
        condition: service_completed_successfully

  terminalserver-api:
    build:
      context: ..
      dockerfile: compose/Dockerfile.be
      args:
        - DOMAIN_NAME=$DOMAIN_NAME
        - APP_SECRET_TOKEN=$APP_SECRET_TOKEN
    command: /usr/local/bin/stustapay terminalserver-api
    restart: on-failure
    depends_on:
      dbupdate:
        condition: service_completed_successfully

  bon-generator:
    build:
      context: ..
      dockerfile: compose/Dockerfile.be
      args:
        - DOMAIN_NAME=$DOMAIN_NAME
        - APP_SECRET_TOKEN=$APP_SECRET_TOKEN
    command: /usr/local/bin/stustapay bon
    restart: on-failure
    depends_on:
      dbupdate:
        condition: service_completed_successfully

  administration-web:
    build:
      context: ..
      dockerfile: compose/Dockerfile.fe
      args:
        - MODULE_NAME=administration
        - DOMAIN_NAME=$DOMAIN_NAME
    restart: on-failure
    depends_on:
      - administration-api
      
  customerportal-web:
    build:
      context: ..
      dockerfile: compose/Dockerfile.fe
      args:
        - MODULE_NAME=customerportal
        - DOMAIN_NAME=$DOMAIN_NAME
    restart: on-failure
    depends_on:
      - customerportal-api
      
  proxy:
    build:
      context: ..
      dockerfile: compose/Dockerfile.proxy
      args:
        - DOMAIN_NAME=$DOMAIN_NAME
    ports:
      - 80:80
      - 443:443
    restart: on-failure
    depends_on:
      - terminalserver-api
      - customerportal-web
      - administration-web

volumes:
  postgres_data:
