name: Core
on:
  workflow_call:
  pull_request:
    paths-ignore:
    - "website/**"
    - "app/**"
    - "web/**"

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install dependencies
        run: python -m pip install -e '.[dev,test]'
      - name: Analysing the code with pylint
        run: make pylint

  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install dependencies
        run: python -m pip install -e '.[dev,test]'
      - name: Analysing the code with mypy
        run: make mypy

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [ 3.11 ]
        os: [ ubuntu-latest ]
        postgres-version: [ 13-bullseye ]
    services:
      postgres:
        image: postgres:${{ matrix.postgres-version }}
        env:
          POSTGRES_PASSWORD: "password"
          POSTGRES_USER: "stustapay"
          POSTGRES_DB: "stustapay-test"
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    env:
      TEST_DB_USER: "stustapay"
      TEST_DB_HOST: "localhost"
      TEST_DB_PORT: "5432"
      TEST_DB_DATABASE: "stustapay-test"
      TEST_DB_PASSWORD: "password"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e '.[dev,test]'
      - name: Run all tests except ones that require latex to be installed
        run: pytest stustapay/tests --doctest-modules --junitxml=junit/test-results.xml --cov=stustapay --cov-report=xml --cov-report=html

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install dependencies
        run: python -m pip install -e '.[dev]'
      - name: Check formatting
        run: make check-format
